// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvB45GeWIlDYe22XzFUlLyc2Ee-GFHTYk',
    appId: '1:203120777153:web:98fe4d0bc1ca65aa6bc140',
    messagingSenderId: '203120777153',
    projectId: 'zegosocial',
    authDomain: 'zegosocial.firebaseapp.com',
    storageBucket: 'zegosocial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTKv9GB5QBnefmn0V_8F6lGRY4Apb1kSw',
    appId: '1:203120777153:android:01230e0e33ca041b6bc140',
    messagingSenderId: '203120777153',
    projectId: 'zegosocial',
    storageBucket: 'zegosocial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkCgwAz5SxQl8G5klH4B04tW2e2QDSJw8',
    appId: '1:203120777153:ios:51d965aedc1db65b6bc140',
    messagingSenderId: '203120777153',
    projectId: 'zegosocial',
    storageBucket: 'zegosocial.appspot.com',
    iosBundleId: 'com.zegosocial.zegosocial',
  );
}
